-- ============================================================
-- GOVERNANÇA DE / ACADEMIA DA FORÇA AÉREA (AFA)
-- SCRIPT MASTER DE CRIAÇÃO E CONFIGURAÇÃO UNIFICADA DO SUPABASE
-- Projeto Oficial: sovrgsbdhdpxsaomspsp
-- ============================================================

-- ------------------------------------------------------------
-- 1. CONFIGURAÇÕES CENTRAIS DO SISTEMA (PIN & INTEGRAÇÕES)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.app_config (
  id TEXT PRIMARY KEY DEFAULT 'default',
  pin TEXT NOT NULL DEFAULT '123456',
  gmail_user TEXT DEFAULT '',
  gmail_app_password TEXT DEFAULT '',
  gmail_sender_name TEXT DEFAULT 'Secretaria DE · AFA',
  gmail_enabled BOOLEAN NOT NULL DEFAULT true,
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.app_config ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Permissao Total Anon app_config" ON public.app_config;
CREATE POLICY "Permissao Total Anon app_config" ON public.app_config FOR ALL USING (true) WITH CHECK (true);

INSERT INTO public.app_config (id, pin, gmail_enabled)
VALUES ('default', '123456', true)
ON CONFLICT (id) DO NOTHING;


-- ------------------------------------------------------------
-- 2. CONFIGURAÇÕES DE ASSINANTES E AUTORIDADES DE OS/OMIS
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.os_config (
  id TEXT PRIMARY KEY DEFAULT 'default',
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  omis_autoridade_nome TEXT DEFAULT 'Odilor da Silva Lopes Cel Int R1',
  omis_autoridade_cargo TEXT DEFAULT 'Adjunto da Divisão de Ensino da AFA',
  omis_autoridade_email TEXT,
  grat_os_autoridade_nome TEXT DEFAULT 'Cel QOINT WELLINGTON MARCELO FERNANDES',
  grat_os_autoridade_cargo TEXT DEFAULT 'Chefe da Divisão Administrativa',
  grat_aut_autoridade_nome TEXT DEFAULT 'GABRIEL HENRIQUES DE OLIVEIRA FARIAS Cel Av',
  grat_aut_autoridade_cargo TEXT DEFAULT 'Chefe da 2SC',
  grat_aut_cidade TEXT DEFAULT 'Brasilia-DF',
  notificar_solicitante_email BOOLEAN DEFAULT true,
  notificar_chefe_omis_email BOOLEAN DEFAULT true
);

ALTER TABLE public.os_config ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Permissao Total Anon os_config" ON public.os_config;
CREATE POLICY "Permissao Total Anon os_config" ON public.os_config FOR ALL USING (true) WITH CHECK (true);

INSERT INTO public.os_config (id)
VALUES ('default')
ON CONFLICT (id) DO NOTHING;


-- ------------------------------------------------------------
-- 3. MÓDULO DE DIÁRIAS (DOTAÇÃO E LANÇAMENTOS)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.diarias_config (
  id TEXT PRIMARY KEY DEFAULT 'default',
  dotacao NUMERIC(12,2) DEFAULT 0,
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.diarias_config ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Permissao Total Anon diarias_config" ON public.diarias_config;
CREATE POLICY "Permissao Total Anon diarias_config" ON public.diarias_config FOR ALL USING (true) WITH CHECK (true);

INSERT INTO public.diarias_config (id, dotacao)
VALUES ('default', 0)
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.diarias_os (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  num TEXT NOT NULL,
  descricao TEXT,
  servidor TEXT NOT NULL,
  data_inicio DATE,
  data_fim DATE,
  qtd_diarias NUMERIC(5,1) DEFAULT 1,
  valor_total NUMERIC(10,2) DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.diarias_os ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Permissao Total Anon diarias_os" ON public.diarias_os;
CREATE POLICY "Permissao Total Anon diarias_os" ON public.diarias_os FOR ALL USING (true) WITH CHECK (true);


-- ------------------------------------------------------------
-- 4. SOLICITAÇÕES DE MISSÃO (PORTAL PÚBLICO)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.solicitacoes_missao (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  protocolo TEXT UNIQUE NOT NULL,
  modalidade TEXT NOT NULL,
  solicita_omis BOOLEAN DEFAULT false,
  solicitante_nome TEXT,
  solicitante_email TEXT,
  coordenador_nome TEXT,
  coordenador_email TEXT,
  militares JSONB NOT NULL DEFAULT '[]'::jsonb,
  servico_local TEXT NOT NULL,
  data_inicio DATE NOT NULL,
  hora_inicio TEXT DEFAULT '04:00',
  data_fim DATE NOT NULL,
  hora_fim TEXT DEFAULT '16:00',
  dias NUMERIC(5,1) DEFAULT 1,
  passagem TEXT DEFAULT 'NÃO',
  apoio_transporte_tipo TEXT DEFAULT 'AFA',
  apoio_transporte_om TEXT,
  apoio_hospedagem_tipo TEXT DEFAULT 'DESTINO',
  apoio_hospedagem_om TEXT,
  apoio_alimentacao_tipo TEXT DEFAULT 'DESTINO',
  apoio_alimentacao_om TEXT,
  apoio_recebido TEXT,
  fora_prazo BOOLEAN DEFAULT false,
  justificativa_prazo TEXT,
  pagamento_antecipado BOOLEAN DEFAULT false,
  justificativa_antecipacao TEXT,
  retorno_apresentado BOOLEAN DEFAULT false,
  retorno_apresentado_em TIMESTAMPTZ,
  retorno_teve_alteracao BOOLEAN DEFAULT false,
  retorno_dados_alteracao JSONB,
  pdf_retorno_assinado TEXT,
  observacoes TEXT,
  status TEXT NOT NULL DEFAULT 'pendente',
  motivo_rejeicao TEXT,
  os_gerada_num TEXT,
  num_omis TEXT
);

ALTER TABLE public.solicitacoes_missao ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Permissao Total Anon solicitacoes_missao" ON public.solicitacoes_missao;
CREATE POLICY "Permissao Total Anon solicitacoes_missao" ON public.solicitacoes_missao FOR ALL USING (true) WITH CHECK (true);


-- ------------------------------------------------------------
-- 5. PROCESSOS DE GRATIFICAÇÃO DE REPRESENTAÇÃO (GRATIREP)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.gratificacao_representacao (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  ano INT NOT NULL DEFAULT EXTRACT(YEAR FROM CURRENT_DATE),
  num_os TEXT NOT NULL,
  num_omis TEXT,
  siloms_numero TEXT,
  comgep_linha TEXT,
  militares JSONB NOT NULL DEFAULT '[]'::jsonb,
  posto_grad TEXT,
  especialidade TEXT,
  nome TEXT,
  nome_guerra TEXT,
  cpf TEXT,
  saram TEXT,
  om TEXT DEFAULT 'AFA',
  data_inicio DATE NOT NULL,
  hora_inicio TEXT DEFAULT '04:00',
  data_fim DATE NOT NULL,
  hora_fim TEXT DEFAULT '16:00',
  dias NUMERIC(5,1) NOT NULL DEFAULT 1,
  passagem TEXT DEFAULT 'NÃO',
  servico_local TEXT NOT NULL,
  apoio_recebido TEXT,
  enquadramento_legal TEXT DEFAULT 'Art 5°, Inc II (Viagem de Instrução)',
  passagens_outra_om TEXT DEFAULT 'Não se aplica.',
  pagamento_antecipado BOOLEAN DEFAULT false,
  justificativa_antecipacao TEXT,
  fora_prazo BOOLEAN DEFAULT false,
  justificativa_prazo TEXT,
  percentual TEXT DEFAULT '2%',
  teve_alteracao_retorno BOOLEAN DEFAULT false,
  justificativa_alteracao_retorno TEXT,
  retorno_dados_alteracao JSONB,
  pdf_retorno_assinado TEXT,
  retorno_apresentado_em TIMESTAMPTZ,
  comandante_nome TEXT DEFAULT 'Cel QOINT WELLINGTON MARCELO FERNANDES',
  comandante_cargo TEXT DEFAULT 'Chefe da Divisão Administrativa',
  chefe_nome TEXT DEFAULT 'GABRIEL HENRIQUES DE OLIVEIRA FARIAS Cel Av',
  chefe_cargo TEXT DEFAULT 'Chefe da 2SC',
  gerou_omis BOOLEAN DEFAULT false,
  omis_autoridade TEXT DEFAULT 'Odilor da Silva Lopes Cel Int R1',
  omis_cargo TEXT DEFAULT 'Adjunto da Divisão de Ensino da AFA',
  omis_enviada BOOLEAN DEFAULT false,
  status TEXT DEFAULT 'Pendente'
);

ALTER TABLE public.gratificacao_representacao ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Permissao Total Anon gratificacao_representacao" ON public.gratificacao_representacao;
CREATE POLICY "Permissao Total Anon gratificacao_representacao" ON public.gratificacao_representacao FOR ALL USING (true) WITH CHECK (true);


-- ------------------------------------------------------------
-- 6. MILITARES EXTERNOS (OUTRAS ORGANIZAÇÕES MILITARES)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.militares_externos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  posto_grad TEXT NOT NULL,
  especialidade TEXT,
  nome_completo TEXT NOT NULL,
  nome_guerra TEXT,
  cpf TEXT NOT NULL,
  saram TEXT,
  om TEXT NOT NULL,
  email TEXT,
  telefone TEXT,
  ativo BOOLEAN DEFAULT true,
  data_confirmacao_dados TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.militares_externos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Permissao Total Anon militares_externos" ON public.militares_externos;
CREATE POLICY "Permissao Total Anon militares_externos" ON public.militares_externos FOR ALL USING (true) WITH CHECK (true);


-- ------------------------------------------------------------
-- 7. ESTEIRA DE CONTROLE DE PROCESSOS OS (COMGEP / 2026)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.controle_os_processos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  ano INT NOT NULL DEFAULT EXTRACT(YEAR FROM CURRENT_DATE),
  num_os TEXT NOT NULL,
  num_omis TEXT,
  modalidade TEXT NOT NULL DEFAULT 'Gratificação',
  coordenador TEXT NOT NULL,
  militares_resumo TEXT,
  servico_local TEXT,
  periodo_inicio DATE,
  periodo_fim DATE,
  sigad_numero TEXT,
  siloms_numero TEXT,
  comgep_linha TEXT,
  status TEXT NOT NULL DEFAULT 'Pendente',
  auditoria TEXT,
  nup TEXT,
  bca_numero TEXT,
  bi_numero TEXT,
  pdf_retorno_assinado TEXT
);

ALTER TABLE public.controle_os_processos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Permissao Total Anon controle_os_processos" ON public.controle_os_processos;
CREATE POLICY "Permissao Total Anon controle_os_processos" ON public.controle_os_processos FOR ALL USING (true) WITH CHECK (true);


-- ------------------------------------------------------------
-- 8. MÓDULO DE CARGOS E FUNÇÕES
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.cargos_secoes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  nome TEXT UNIQUE NOT NULL,
  sigla TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.cargos_catalogo (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  secao_id UUID REFERENCES public.cargos_secoes(id) ON DELETE CASCADE,
  tipo TEXT NOT NULL CHECK (tipo IN ('cargo', 'funcao')),
  nome TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.cargos_militares_ativos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  saram TEXT UNIQUE NOT NULL,
  posto_grad TEXT,
  nome TEXT NOT NULL,
  cpf TEXT,
  secao_id UUID REFERENCES public.cargos_secoes(id) ON DELETE SET NULL,
  secao_nome TEXT,
  tipo TEXT CHECK (tipo IN ('cargo', 'funcao')),
  cargo_funcao_nome TEXT,
  data_assuncao DATE,
  boletim_publicacao TEXT,
  boletim_data DATE,
  siloms_num TEXT,
  origem TEXT DEFAULT 'sistema',
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.cargos_solicitacoes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  tipo TEXT NOT NULL CHECK (tipo IN ('cargo', 'funcao')),
  acao_tipo TEXT DEFAULT 'designacao',
  secao_id UUID REFERENCES public.cargos_secoes(id) ON DELETE SET NULL,
  secao_nome TEXT NOT NULL,
  cargo_funcao_nome TEXT NOT NULL,
  solicitante_nome TEXT,
  solicitante_saram TEXT,
  solicitante_cpf TEXT,
  solicitante_email TEXT,
  militar_designado_nome TEXT,
  militar_designado_saram TEXT,
  militar_designado_posto TEXT,
  militar_designado_cpf TEXT,
  militar_dispensado_nome TEXT,
  militar_dispensado_saram TEXT,
  militar_dispensado_posto TEXT,
  militar_dispensado_cpf TEXT,
  data_inicio DATE,
  status_funcao TEXT DEFAULT 'pendente',
  status_cargo TEXT DEFAULT 'pendente',
  boletim_numero TEXT,
  boletim_data DATE,
  boletim_arquivo_url TEXT,
  boletim_arquivo_nome TEXT,
  siloms_processo_num TEXT,
  siloms_status TEXT DEFAULT 'pendente',
  ttac_pendente BOOLEAN DEFAULT false,
  motivo_codigo TEXT,
  observacoes TEXT
);

CREATE TABLE IF NOT EXISTS public.cargos_config (
  id TEXT PRIMARY KEY DEFAULT 'default',
  pin TEXT DEFAULT '123456',
  motivo_cargo_designacao TEXT DEFAULT '1138',
  motivo_cargo_dispensa TEXT DEFAULT '1139',
  motivo_funcao_designacao TEXT DEFAULT '9208',
  motivo_funcao_dispensa TEXT DEFAULT '9209',
  email_sreg TEXT DEFAULT 'sreg.afa@fab.mil.br',
  texto_padrao_email_sreg TEXT DEFAULT 'Prezado Senhores,\n\nSolicito o TTAC e a relação de carga da Seção {SECAO}, conforme publicado no boletim n°{BOLETIM_NUM} de {BOLETIM_DATA} dos respectivos militares:\nDispensa: {MILITAR_DISP}\nDesignação: {MILITAR_DESIG}.\n\nAtenciosamente,\nSecretaria da Divisão de Ensino - AFA',
  updated_at TIMESTAMPTZ DEFAULT now()
);

INSERT INTO public.cargos_config (id, pin, motivo_cargo_designacao, motivo_cargo_dispensa, motivo_funcao_designacao, motivo_funcao_dispensa, email_sreg)
VALUES ('default', '123456', '1138', '1139', '9208', '9209', 'sreg.afa@fab.mil.br')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.cargos_secoes (nome, sigla)
VALUES 
  ('Divisão de Ensino', 'DE'),
  ('Subdivisão de Instrução Militar', 'SDINT'),
  ('Subdivisão de Instrução Geral', 'SDIR'),
  ('Célula de Infraestrutura ao Ensino', 'CEL-INFRA'),
  ('Secretaria da Divisão de Ensino', 'SEC-DE'),
  ('Célula de Planejamento e Avaliação', 'CEL-PLAN')
ON CONFLICT (nome) DO NOTHING;

ALTER TABLE public.cargos_secoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cargos_catalogo ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cargos_militares_ativos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cargos_solicitacoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cargos_config ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Permissao Total Anon cargos_secoes" ON public.cargos_secoes;
CREATE POLICY "Permissao Total Anon cargos_secoes" ON public.cargos_secoes FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Permissao Total Anon cargos_catalogo" ON public.cargos_catalogo;
CREATE POLICY "Permissao Total Anon cargos_catalogo" ON public.cargos_catalogo FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Permissao Total Anon cargos_militares_ativos" ON public.cargos_militares_ativos;
CREATE POLICY "Permissao Total Anon cargos_militares_ativos" ON public.cargos_militares_ativos FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Permissao Total Anon cargos_solicitacoes" ON public.cargos_solicitacoes;
CREATE POLICY "Permissao Total Anon cargos_solicitacoes" ON public.cargos_solicitacoes FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Permissao Total Anon cargos_config" ON public.cargos_config;
CREATE POLICY "Permissao Total Anon cargos_config" ON public.cargos_config FOR ALL USING (true) WITH CHECK (true);


-- ------------------------------------------------------------
-- 9. MÓDULO TACF (TESTE DE AVALIAÇÃO DO CONDICIONAMENTO FÍSICO)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.tacf_temporadas (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  ano INT NOT NULL DEFAULT EXTRACT(YEAR FROM CURRENT_DATE),
  semestre INT NOT NULL DEFAULT 1,
  titulo TEXT NOT NULL DEFAULT '1º/2026',
  status TEXT NOT NULL DEFAULT 'agendamento_fechado',
  datas_aplicacao JSONB NOT NULL DEFAULT '[]'::jsonb,
  vagas_por_dia INT NOT NULL DEFAULT 4,
  vagas_livres_reserva INT NOT NULL DEFAULT 3,
  observacoes TEXT
);

CREATE TABLE IF NOT EXISTS public.tacf_solicitacoes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  temporada_id UUID REFERENCES public.tacf_temporadas(id) ON DELETE CASCADE,
  saram TEXT NOT NULL,
  cpf TEXT,
  posto_grad TEXT NOT NULL,
  especialidade TEXT,
  nome_guerra TEXT NOT NULL,
  nome_completo TEXT,
  antiguidade_index INT DEFAULT 999,
  prio1_data DATE,
  prio2_data DATE,
  prio3_data DATE,
  indisponibilidades JSONB NOT NULL DEFAULT '[]'::jsonb,
  dia_escalado DATE,
  metodo_alocacao TEXT,
  status_solicitacao TEXT NOT NULL DEFAULT 'pendente',
  status_elegibilidade TEXT NOT NULL DEFAULT 'elegivel',
  justificativa TEXT,
  data_realizacao DATE,
  CONSTRAINT unique_militar_temporada UNIQUE (temporada_id, saram)
);

ALTER TABLE public.tacf_temporadas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tacf_solicitacoes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Permissao Total Anon tacf_temporadas" ON public.tacf_temporadas;
CREATE POLICY "Permissao Total Anon tacf_temporadas" ON public.tacf_temporadas FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Permissao Total Anon tacf_solicitacoes" ON public.tacf_solicitacoes;
CREATE POLICY "Permissao Total Anon tacf_solicitacoes" ON public.tacf_solicitacoes FOR ALL USING (true) WITH CHECK (true);


-- ------------------------------------------------------------
-- 10. MÓDULO DE MANUTENÇÃO PREDIAL
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.mnt_chamados (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  local_id TEXT NOT NULL,
  titulo TEXT NOT NULL,
  sistema TEXT NOT NULL,
  prioridade TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'aberto',
  descricao TEXT,
  solicitante TEXT,
  prazo DATE,
  aberto_em TIMESTAMPTZ DEFAULT now(),
  concluido_em TIMESTAMPTZ
);

ALTER TABLE public.mnt_chamados ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Permissao Total Anon mnt_chamados" ON public.mnt_chamados;
CREATE POLICY "Permissao Total Anon mnt_chamados" ON public.mnt_chamados FOR ALL USING (true) WITH CHECK (true);


-- ------------------------------------------------------------
-- 11. MÓDULO AUXÍLIO TRANSPORTE (at_oficios)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.at_oficios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  competencia TEXT UNIQUE NOT NULL,
  num_oficio TEXT DEFAULT '',
  num_sigad TEXT DEFAULT '',
  email_enviado_em TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.at_oficios ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Permissao Total Anon at_oficios" ON public.at_oficios;
CREATE POLICY "Permissao Total Anon at_oficios" ON public.at_oficios FOR ALL USING (true) WITH CHECK (true);


-- ------------------------------------------------------------
-- 12. STORAGE BUCKET: BOLETINS (PDF-A)
-- ------------------------------------------------------------
INSERT INTO storage.buckets (id, name, public)
VALUES ('boletins', 'boletins', true)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "Permitir upload boletins" ON storage.objects;
CREATE POLICY "Permitir upload boletins" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'boletins');

DROP POLICY IF EXISTS "Permitir leitura boletins" ON storage.objects;
CREATE POLICY "Permitir leitura boletins" ON storage.objects FOR SELECT USING (bucket_id = 'boletins');

DROP POLICY IF EXISTS "Permitir update boletins" ON storage.objects;
CREATE POLICY "Permitir update boletins" ON storage.objects FOR UPDATE USING (bucket_id = 'boletins');

DROP POLICY IF EXISTS "Permitir delete boletins" ON storage.objects;
CREATE POLICY "Permitir delete boletins" ON storage.objects FOR DELETE USING (bucket_id = 'boletins');
