-- ============================================================
-- ESTRUTURA DE TABELAS PARA O MÓDULO AUXÍLIO TRANSPORTE (at_oficios)
-- Governança DE / Academia da Força Aérea
-- ============================================================

CREATE TABLE IF NOT EXISTS public.at_oficios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  competencia TEXT UNIQUE NOT NULL,
  num_oficio TEXT DEFAULT '',
  num_sigad TEXT DEFAULT '',
  email_enviado_em TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Adiciona a coluna email_enviado_em se a tabela já existia sem ela
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema = 'public' AND table_name = 'at_oficios' AND column_name = 'email_enviado_em'
  ) THEN
    ALTER TABLE public.at_oficios ADD COLUMN email_enviado_em TIMESTAMPTZ;
  END IF;
END $$;

-- Garantir constraint de unicidade em competencia
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'at_oficios_competencia_key'
  ) THEN
    ALTER TABLE public.at_oficios ADD CONSTRAINT at_oficios_competencia_key UNIQUE (competencia);
  END IF;
EXCEPTION
  WHEN OTHERS THEN NULL;
END $$;

-- Ativar Row Level Security (RLS)
ALTER TABLE public.at_oficios ENABLE ROW LEVEL SECURITY;

-- Políticas de acesso anônimo para at_oficios
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'at_oficios' AND policyname = 'Permitir leitura anonima em at_oficios'
  ) THEN
    CREATE POLICY "Permitir leitura anonima em at_oficios"
    ON public.at_oficios FOR SELECT USING (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'at_oficios' AND policyname = 'Permitir insercao anonima em at_oficios'
  ) THEN
    CREATE POLICY "Permitir insercao anonima em at_oficios"
    ON public.at_oficios FOR INSERT WITH CHECK (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'at_oficios' AND policyname = 'Permitir edicao anonima em at_oficios'
  ) THEN
    CREATE POLICY "Permitir edicao anonima em at_oficios"
    ON public.at_oficios FOR UPDATE USING (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'at_oficios' AND policyname = 'Permitir exclusao anonima em at_oficios'
  ) THEN
    CREATE POLICY "Permitir exclusao anonima em at_oficios"
    ON public.at_oficios FOR DELETE USING (true);
  END IF;
END $$;
